#!/usr/bin/env bash
# Instal nginx on a web server with specific configs

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
