#!/usr/bin/env bash
# Load balancer to Configure HAproxy so that it send traffic to web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend cyril-777.tech-frontend
        bind *:80
        mode http
        default_backend cyril-777.tech-backend
backend cyril-777.tech-backend
        balance roundrobin
        server 199194-web-01 54.173.134.61 check
        server 199194-web-02 54.89.133.85 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
