#!/usr/bin/env bash
# debugging nginx to run and listen to port 80
# service (init) must say that nginx is not running
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
