#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

echo $$ > /var/run/myscript.pid

trap 'echo Y U no love me?!' SIGINT
trap 'echo I hate the kill command' SIGTERM
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 1
done
