#!/usr/bin/env bash
# nginx be running as nginx user and listening on all active IPs on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
